# Permalinks
permalink:           pretty

# Setup
title:               Swear of the Month
tagline:             Putting filthy things in your mouth, monthly.
url:                 http://getpoole.com
paginate:            12
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Cory O'Brien
  url:               https://twitter.com/bettermyths
  email:             cory@swearofthemonth.club

# Custom vars
version:             2.0.0
github:
  repo:

# Gems
plugins:
  - jekyll-paginate
  - jekyll-gist
